services:
  app:
    image: spring-cloud-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - gateway-network
    restart: always
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY=0
    networks:
      - gateway-network
    restart: always
networks:
  gateway-network:
    driver: bridge
